name: CI Workflow 
on: [push, pull_request] 
jobs: 
  build: 
    runs-on: self-ubuntu-24.04
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        run: latexmk -pdf main.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-pdf
          path: main.pdf
      